# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c1fda839df62fd6f7247fe06981bc6adfe02d8d9f10154d0d8074d3b85aa8ab608f2f606249833b182c2487e366bacdb889cd37def7080c14c84faa0c53c459

test:
  secret_key_base: f6ea6c9b47f622f21ad10f126c12c9c7e37ed10dd015591a5b43b4cd20743e0c34df0310c4b872217522f1e9bffcca6de2405eec7baf580e90fae325614df072

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
